"""Gcode file analyzer -- extracts slicer settings and statistics from .gcode files."""

import logging
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Set, Union

from core.constants import (
    GCODE_CONFIG_END,
    GCODE_CONFIG_START,
    GCODE_HEADER_END,
    GCODE_OBJECT_MARKER,
    HEADER_LINES_LIMIT,
    TAIL_READ_SIZE,
    build_common_profile,
)

logger = logging.getLogger(__name__)


class GcodeAnalyzer:
    """Analyzes Gcode files and extracts slicer settings and statistics.

    Parses gcode files generated by OrcaSlicer, Bambu Studio, Snapmaker Orca,
    and other compatible slicers. Uses block markers for efficient parsing.
    """

    def __init__(self, filepath: Union[str, Path]):
        self.filepath = Path(filepath)
        self.settings: Dict[str, str] = {}
        self.header_info: Dict[str, str] = {}
        self.statistics: Dict[str, Any] = {}
        self.object_names: Set[str] = set()

    def analyze(self) -> Dict[str, Any]:
        """Main analysis method. Extracts settings and statistics from gcode file.

        Returns:
            Dict containing profile, settings, statistics, and object names.

        Raises:
            OSError: If the file cannot be read.
        """
        logger.debug("Starting gcode analysis of file: %s", self.filepath)

        if not self.filepath.exists():
            raise OSError(f"File not found: {self.filepath}")

        self._parse_gcode()
        result = self._build_result()
        logger.debug("Successfully analyzed gcode file")
        return result

    def _parse_gcode(self):
        """Parse gcode file using block markers for efficient parsing."""
        file_size = os.path.getsize(self.filepath)

        # Read file in chunks from the end to find CONFIG_BLOCK
        # Most gcode files have settings at the end
        with open(self.filepath, 'r', encoding='utf-8', errors='replace') as f:
            # First, read header (first HEADER_LINES_LIMIT lines)
            header_lines = []
            for i, line in enumerate(f):
                if i >= HEADER_LINES_LIMIT:
                    break
                header_lines.append(line)
                if line.strip() == GCODE_HEADER_END:
                    break

            self._parse_header(header_lines)

            # Reset and scan for object markers (scan entire file for this)
            f.seek(0)
            for line in f:
                if line.startswith(GCODE_OBJECT_MARKER):
                    self._extract_object_name(line)

            # Now find and parse CONFIG_BLOCK from end of file
            # Read last portion of file (settings are typically in last ~100KB)
            f.seek(0, 2)  # Go to end
            file_end = f.tell()
            read_size = min(TAIL_READ_SIZE, file_end)
            f.seek(max(0, file_end - read_size))

            tail_content = f.read()
            self._parse_config_block(tail_content)
            self._parse_statistics(tail_content)

        # Add file size to statistics
        self.statistics['file_size_bytes'] = file_size

    def _parse_header(self, lines: List[str]):
        """Parse header block for basic info.

        Header format:
        ; generated by Snapmaker Orca 2.2.1 on 2026-01-30 at 12:34:13
        ; total layer number: 138
        ; max_z_height: 22.12
        """
        for line in lines:
            line = line.strip()
            if not line.startswith(';'):
                continue

            content = line[1:].strip()

            # Parse "generated by" line
            if content.startswith('generated by '):
                match = re.match(
                    r'generated by (.+?) (\d+\.\d+\.\d+) on (\d{4}-\d{2}-\d{2}) at (\d{2}:\d{2}:\d{2})',
                    content
                )
                if match:
                    self.header_info['slicer'] = match.group(1)
                    self.header_info['slicer_version'] = match.group(2)
                    self.header_info['generated_date'] = f"{match.group(3)} {match.group(4)}"

            # Parse key: value pairs in header
            elif ':' in content and '=' not in content:
                key, _, value = content.partition(':')
                key = key.strip().lower().replace(' ', '_')
                value = value.strip()
                self.header_info[key] = value

    def _extract_object_name(self, line: str):
        """Extract object name from '; printing object NAME id:XXX' marker."""
        # Format: ; printing object NAME id:123456 copy N
        content = line[len(GCODE_OBJECT_MARKER):].strip()
        # Remove id:xxx and copy N parts
        match = re.match(r'(.+?)\s+id:\d+', content)
        if match:
            obj_name = match.group(1).strip()
            self.object_names.add(obj_name)

    def _parse_config_block(self, content: str):
        """Parse CONFIG_BLOCK section for all settings.

        Settings format:
        ; setting_key = value
        """
        in_config = False

        for line in content.split('\n'):
            line = line.strip()

            if line == GCODE_CONFIG_START:
                in_config = True
                continue
            elif line == GCODE_CONFIG_END:
                break

            if in_config and line.startswith('; ') and ' = ' in line:
                # Parse setting line: ; key = value
                setting_line = line[2:]  # Remove "; "
                key, _, value = setting_line.partition(' = ')
                key = key.strip()
                value = value.strip()
                self.settings[key] = value

    def _parse_statistics(self, content: str):
        """Parse statistics from gcode (before CONFIG_BLOCK).

        Statistics format:
        ; filament used [g] = 10.08, 0.87, 0.31
        ; total filament used [g] = 11.26
        ; estimated printing time (normal mode) = 1h 11m 17s
        """
        # Statistics patterns (these appear before CONFIG_BLOCK)
        patterns = {
            'filament_used_g': r'^; filament used \[g\] = (.+)$',
            'filament_used_mm': r'^; filament used \[mm\] = (.+)$',
            'filament_used_cm3': r'^; filament used \[cm3\] = (.+)$',
            'filament_cost_per_extruder': r'^; filament cost = (.+)$',
            'total_filament_used_g': r'^; total filament used \[g\] = (.+)$',
            'total_filament_cost': r'^; total filament cost = (.+)$',
            'total_filament_change': r'^; total filament change = (\d+)$',
            'total_layers_count': r'^; total layers count = (\d+)$',
            'estimated_time': r'^; estimated printing time \(normal mode\) = (.+)$',
            'estimated_first_layer_time': r'^; estimated first layer printing time \(normal mode\) = (.+)$',
        }

        for line in content.split('\n'):
            line = line.strip()
            for key, pattern in patterns.items():
                match = re.match(pattern, line)
                if match:
                    value = match.group(1).strip()
                    # Parse numeric values
                    if key in ('total_filament_used_g', 'total_filament_cost'):
                        try:
                            self.statistics[key] = float(value)
                        except ValueError:
                            self.statistics[key] = value
                    elif key in ('total_filament_change', 'total_layers_count'):
                        try:
                            self.statistics[key] = int(value)
                        except ValueError:
                            self.statistics[key] = value
                    elif key in ('filament_used_g', 'filament_used_mm', 'filament_used_cm3',
                                  'filament_cost_per_extruder'):
                        # Parse comma-separated list of floats
                        try:
                            self.statistics[key] = [float(v.strip()) for v in value.split(',')]
                        except ValueError:
                            self.statistics[key] = value
                    else:
                        self.statistics[key] = value
                    break

    def _get_value(self, key: str, default: Any = None) -> Any:
        """Get value from settings, handling list formats.

        Gcode settings often have comma-separated values for multi-extruder setups.
        This method returns the first value for such settings.
        """
        value = self.settings.get(key, default)
        if value is None:
            return default

        # Handle semicolon-separated list (filament names)
        if ';' in str(value):
            parts = [p.strip().strip('"') for p in str(value).split(';') if p.strip()]
            return parts[0] if parts else default

        # Handle comma-separated list (numeric values)
        if ',' in str(value):
            parts = [p.strip() for p in str(value).split(',') if p.strip()]
            return parts[0] if parts else default

        return value

    def _get_list_value(self, key: str, default: Any = None) -> List[str]:
        """Get list value from settings."""
        value = self.settings.get(key)
        if value is None:
            return default if default is not None else []

        # Handle semicolon-separated list (filament names)
        if ';' in str(value):
            return [p.strip().strip('"') for p in str(value).split(';') if p.strip()]

        # Handle comma-separated list
        if ',' in str(value):
            return [p.strip() for p in str(value).split(',') if p.strip()]

        return [str(value)]

    def _get_custom_global_settings(self) -> Dict[str, Any]:
        """Extract custom global settings from different_settings_to_system."""
        custom = {}

        diff_settings = self.settings.get('different_settings_to_system', '')
        if diff_settings:
            keys = [k.strip() for k in diff_settings.split(';') if k.strip()]
            for key in keys:
                if key in self.settings:
                    custom[key] = self.settings[key]

        return custom

    def _get_profile_info(self) -> Dict[str, Any]:
        """Extract profile information matching ThreeMFAnalyzer format."""
        profile = build_common_profile(self._get_value)
        profile['printer'] = self.settings.get('printer_settings_id', 'Unknown')
        profile['process'] = self.settings.get('print_settings_id', 'Unknown')
        profile['filaments'] = self._get_list_value('filament_settings_id', ['Unknown'])
        # Gcode uses 'first_layer_height' instead of 'initial_layer_print_height'
        profile['initial_layer_print_height'] = self._get_value('first_layer_height', '')
        return profile

    def _build_statistics(self) -> Dict[str, Any]:
        """Build comprehensive statistics dictionary."""
        stats = {}

        # Slicer info from header
        stats['slicer'] = self.header_info.get('slicer', '')
        stats['slicer_version'] = self.header_info.get('slicer_version', '')
        stats['generated_date'] = self.header_info.get('generated_date', '')

        # Time estimates
        stats['estimated_time'] = self.statistics.get('estimated_time', '')
        stats['estimated_first_layer_time'] = self.statistics.get('estimated_first_layer_time', '')

        # Layer info
        try:
            stats['total_layers'] = (
                self.statistics.get('total_layers_count')
                or int(self.header_info.get('total_layer_number', 0) or 0)
            )
        except (ValueError, TypeError):
            stats['total_layers'] = 0
        try:
            stats['max_height'] = float(self.header_info.get('max_z_height', 0) or 0)
        except (ValueError, TypeError):
            stats['max_height'] = 0.0
        stats['layer_height'] = self._get_value('layer_height', '')
        stats['first_layer_height'] = self._get_value('first_layer_height', '')

        # Nozzle
        stats['nozzle_diameter'] = self._get_list_value('nozzle_diameter', [])

        # Filament usage
        stats['filament_used_g'] = self.statistics.get('total_filament_used_g', 0)
        stats['filament_used_per_extruder_g'] = self.statistics.get('filament_used_g', [])
        stats['filament_used_per_extruder_mm'] = self.statistics.get('filament_used_mm', [])
        stats['filament_cost'] = self.statistics.get('total_filament_cost', 0)
        stats['filament_cost_per_extruder'] = self.statistics.get('filament_cost_per_extruder', [])
        stats['filament_changes'] = self.statistics.get('total_filament_change', 0)

        # Filament info
        stats['filament_names'] = self._get_list_value('filament_settings_id', [])
        stats['filament_types'] = self._get_list_value('filament_type', [])
        stats['filament_colors'] = self._get_list_value('filament_colour', [])
        stats['filament_density'] = self._get_list_value('filament_density', [])
        stats['filament_diameter'] = self._get_list_value('filament_diameter', [])

        # Temperatures
        stats['first_layer_bed_temp'] = self._get_value('first_layer_bed_temperature', '') or \
                                         self._get_value('hot_plate_temp_initial_layer', '')
        stats['first_layer_nozzle_temp'] = self._get_value('first_layer_temperature', '') or \
                                            self._get_value('nozzle_temperature_initial_layer', '')
        stats['nozzle_temp'] = self._get_list_value('nozzle_temperature', [])
        stats['bed_temp'] = self._get_value('hot_plate_temp', '') or \
                            self._get_value('bed_temperature', '')

        # Printer/Machine info
        stats['printer_model'] = self._get_value('printer_model', '')
        stats['gcode_flavor'] = self._get_value('gcode_flavor', '')
        stats['nozzle_type'] = self._get_value('nozzle_type', '')
        stats['curr_bed_type'] = self._get_value('curr_bed_type', '')

        # Filament extra
        stats['filament_vendor'] = self._get_list_value('filament_vendor', [])
        stats['filament_used_per_extruder_cm3'] = self.statistics.get('filament_used_cm3', [])
        stats['enable_prime_tower'] = self._get_value('enable_prime_tower', '')

        # File size
        stats['file_size_bytes'] = self.statistics.get('file_size_bytes', 0)

        return stats

    def _build_result(self) -> Dict[str, Any]:
        """Build the result dictionary."""
        return {
            'file': str(self.filepath.name),
            'profile': self._get_profile_info(),
            'profile_full': self.settings,
            'custom_global': self._get_custom_global_settings(),
            'rows': [],  # Gcode doesn't have per-object settings
            'objects': sorted(self.object_names),  # Object names list
            'statistics': self._build_statistics(),
        }
