"""Gcode file analyzer -- extracts slicer settings and statistics from .gcode files."""

import logging
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Set, Union

from core.constants import (
    BED_TYPE_TEMP_KEYS,
    BED_TYPE_TEMP_KEYS_DEFAULT,
    GCODE_CONFIG_END,
    GCODE_CONFIG_START,
    GCODE_HEADER_END,
    GCODE_OBJECT_MARKER,
    GCODE_PARSE_CONFIG,
    GCODE_THUMBNAIL_END,
    GCODE_THUMBNAIL_START,
    HEADER_LINES_LIMIT,
    MAX_GCODE_LINE_LENGTH,
    TAIL_READ_SIZE,
    build_common_profile,
)

logger = logging.getLogger(__name__)


class GcodeAnalyzer:
    """Analyzes Gcode files and extracts slicer settings and statistics.

    Parses gcode files generated by OrcaSlicer, Bambu Studio, Snapmaker Orca,
    and other compatible slicers. Uses block markers for efficient parsing.
    """

    def __init__(self, filepath: Union[str, Path]):
        self.filepath = Path(filepath)
        self.settings: Dict[str, str] = {}
        self.header_info: Dict[str, str] = {}
        self.statistics: Dict[str, Any] = {}
        self.object_names: Set[str] = set()

    def analyze(self) -> Dict[str, Any]:
        """Main analysis method. Extracts settings and statistics from gcode file.

        Returns:
            Dict containing profile, settings, statistics, and object names.

        Raises:
            OSError: If the file cannot be read.
        """
        logger.debug("Starting gcode analysis of file: %s", self.filepath)

        if not self.filepath.exists():
            raise OSError(f"File not found: {self.filepath}")

        self._parse_gcode()
        result = self._build_result()
        logger.debug("Successfully analyzed gcode file")
        return result

    def _parse_gcode(self):
        """Parse gcode file in a single pass with section-aware processing.
        
        Optimized approach:
        - Single pass through the file (vs 3 passes in old implementation)
        - Skip thumbnail sections (base64-encoded images)
        - Process only relevant sections based on GCODE_PARSE_CONFIG
        - Add safety check for malformed files (line length limit)
        """
        file_size = os.path.getsize(self.filepath)
        config = GCODE_PARSE_CONFIG
        
        # Section tracking
        current_section = None
        in_thumbnail = False
        in_config = False
        line_count = 0
        statistics_lines = []  # Collect statistics lines before CONFIG_BLOCK
        
        with open(self.filepath, 'r', encoding='utf-8', errors='replace') as f:
            for line in f:
                line_count += 1
                
                # Safety check for malformed files
                if len(line) > MAX_GCODE_LINE_LENGTH:
                    logger.warning(
                        "Line %d exceeds maximum length (%d bytes), stopping parse for safety",
                        line_count, MAX_GCODE_LINE_LENGTH
                    )
                    break
                
                # === SECTION DETECTION ===
                stripped = line.strip()
                
                # Thumbnail section markers
                if GCODE_THUMBNAIL_START in line:
                    in_thumbnail = True
                    continue
                if GCODE_THUMBNAIL_END in line:
                    in_thumbnail = False
                    continue
                
                # CONFIG_BLOCK markers
                if stripped == GCODE_CONFIG_START:
                    in_config = True
                    continue
                if stripped == GCODE_CONFIG_END:
                    # Finished parsing - no need to read rest of file
                    break
                
                # === SKIP UNWANTED SECTIONS ===
                if in_thumbnail and config['skip_thumbnails']:
                    continue  # Skip base64 thumbnail data
                
                # === PROCESS BY SECTION ===
                
                # CONFIG_BLOCK section
                if in_config and config['parse_config']:
                    if stripped.startswith('; ') and ' = ' in stripped:
                        setting_line = stripped[2:]  # Remove "; "
                        key, _, value = setting_line.partition(' = ')
                        self.settings[key.strip()] = value.strip()
                    continue
                
                # Header and executable sections (everything before CONFIG_BLOCK)
                if not in_config and stripped.startswith(';'):
                    content = stripped[1:].strip()
                    
                    # Header metadata (first ~100 lines)
                    if line_count <= HEADER_LINES_LIMIT and config['parse_headers']:
                        self._parse_header_line(content)
                    
                    # Object markers (throughout executable section)
                    if config['extract_objects'] and stripped.startswith(GCODE_OBJECT_MARKER):
                        self._extract_object_name(stripped)
                    
                    # Statistics lines (appear before CONFIG_BLOCK)
                    if config['parse_statistics']:
                        # Collect lines that might be statistics
                        if any(marker in content for marker in [
                            'filament used', 'filament cost', 'estimated printing time',
                            'total layers count', 'filament change'
                        ]):
                            statistics_lines.append(stripped)
        
        # Parse collected statistics
        if config['parse_statistics'] and statistics_lines:
            self._parse_statistics_lines(statistics_lines)
        
        # Add file size to statistics
        self.statistics['file_size_bytes'] = file_size
        logger.debug("Parsed %d lines from gcode file", line_count)

    def _parse_header_line(self, content: str):
        """Parse a single header line."""
        # Parse "generated by" line
        if content.startswith('generated by '):
            match = re.match(
                r'generated by (.+?) (\d+\.\d+\.\d+) on (\d{4}-\d{2}-\d{2}) at (\d{2}:\d{2}:\d{2})',
                content
            )
            if match:
                self.header_info['slicer'] = match.group(1)
                self.header_info['slicer_version'] = match.group(2)
                self.header_info['generated_date'] = f"{match.group(3)} {match.group(4)}"
        
        # Parse key: value pairs in header
        elif ':' in content and '=' not in content:
            key, _, value = content.partition(':')
            key = key.strip().lower().replace(' ', '_')
            value = value.strip()
            self.header_info[key] = value

    def _parse_statistics_lines(self, lines: List[str]):
        """Parse statistics from collected comment lines."""
        patterns = {
            'filament_used_g': r'^; filament used \[g\] = (.+)$',
            'filament_used_mm': r'^; filament used \[mm\] = (.+)$',
            'filament_used_cm3': r'^; filament used \[cm3\] = (.+)$',
            'filament_cost_per_extruder': r'^; filament cost = (.+)$',
            'total_filament_used_g': r'^; total filament used \[g\] = (.+)$',
            'total_filament_cost': r'^; total filament cost = (.+)$',
            'total_filament_change': r'^; total filament change = (\d+)$',
            'total_layers_count': r'^; total layers count = (\d+)$',
            'estimated_time': r'^; estimated printing time \(normal mode\) = (.+)$',
            'estimated_first_layer_time': r'^; estimated first layer printing time \(normal mode\) = (.+)$',
        }
        
        for line in lines:
            for key, pattern in patterns.items():
                match = re.match(pattern, line)
                if match:
                    value = match.group(1).strip()
                    # Parse numeric values
                    if key in ('total_filament_used_g', 'total_filament_cost'):
                        try:
                            self.statistics[key] = float(value)
                        except ValueError:
                            self.statistics[key] = value
                    elif key in ('total_filament_change', 'total_layers_count'):
                        try:
                            self.statistics[key] = int(value)
                        except ValueError:
                            self.statistics[key] = value
                    elif key in ('filament_used_g', 'filament_used_mm', 'filament_used_cm3',
                                  'filament_cost_per_extruder'):
                        # Parse comma-separated list of floats
                        try:
                            self.statistics[key] = [float(v.strip()) for v in value.split(',')]
                        except ValueError:
                            self.statistics[key] = value
                    else:
                        self.statistics[key] = value
                    break

    def _extract_object_name(self, line: str):
        """Extract object name from '; printing object NAME id:XXX' marker."""
        # Format: ; printing object NAME id:123456 copy N
        content = line[len(GCODE_OBJECT_MARKER):].strip()
        # Remove id:xxx and copy N parts
        match = re.match(r'(.+?)\s+id:\d+', content)
        if match:
            obj_name = match.group(1).strip()
            self.object_names.add(obj_name)

    def _get_value(self, key: str, default: Any = None) -> Any:
        """Get value from settings, handling list formats.

        Gcode settings often have comma-separated values for multi-extruder setups.
        This method returns the first value for such settings.
        """
        value = self.settings.get(key, default)
        if value is None:
            return default

        # Handle semicolon-separated list (filament names)
        if ';' in str(value):
            parts = [p.strip().strip('"') for p in str(value).split(';') if p.strip()]
            return parts[0] if parts else default

        # Handle comma-separated list (numeric values)
        if ',' in str(value):
            parts = [p.strip() for p in str(value).split(',') if p.strip()]
            return parts[0] if parts else default

        return value

    def _get_list_value(self, key: str, default: Any = None) -> List[str]:
        """Get list value from settings."""
        value = self.settings.get(key)
        if value is None:
            return default if default is not None else []

        # Handle semicolon-separated list (filament names)
        if ';' in str(value):
            return [p.strip().strip('"') for p in str(value).split(';') if p.strip()]

        # Handle comma-separated list
        if ',' in str(value):
            return [p.strip() for p in str(value).split(',') if p.strip()]

        return [str(value)]

    def _get_active_filament_count(self) -> int:
        """Return the number of active filaments based on filament_settings_id.

        ``filament_settings_id`` in Gcode is semicolon-separated when multiple
        filaments are used (e.g. ``"Generic PLA";"Bambu PETG"``).
        """
        raw = self.settings.get('filament_settings_id', '')
        if not raw:
            return 1
        parts = [p.strip().strip('"') for p in raw.split(';') if p.strip()]
        return max(len(parts), 1)

    def _get_custom_global_settings(self) -> Dict[str, Any]:
        """Extract custom global settings from different_settings_to_system.

        For multi-filament prints, comma-separated values are trimmed to only
        the active filament count and labelled when values differ between
        filaments (e.g. ``F1: 12, F2: 6``).
        """
        custom: Dict[str, Any] = {}

        diff_settings = self.settings.get('different_settings_to_system', '')
        if not diff_settings:
            return custom

        n_filaments = self._get_active_filament_count()
        keys = [k.strip() for k in diff_settings.split(';') if k.strip()]

        for key in keys:
            if key not in self.settings:
                continue
            raw = self.settings[key]

            if ',' in str(raw):
                parts = [p.strip() for p in str(raw).split(',')]
                active = parts[:n_filaments]
                if len(active) == 1 or len(set(active)) == 1:
                    custom[key] = active[0]
                else:
                    custom[key] = ', '.join(
                        f"F{i + 1}: {v}" for i, v in enumerate(active)
                    )
            else:
                custom[key] = raw

        return custom

    def _get_profile_info(self) -> Dict[str, Any]:
        """Extract profile information matching ThreeMFAnalyzer format."""
        profile = build_common_profile(self._get_value)
        profile['printer'] = self.settings.get('printer_settings_id', 'Unknown')
        profile['process'] = self.settings.get('print_settings_id', 'Unknown')
        profile['filaments'] = self._get_list_value('filament_settings_id', ['Unknown'])
        # Gcode uses 'first_layer_height' instead of 'initial_layer_print_height'
        profile['initial_layer_print_height'] = self._get_value('first_layer_height', '')
        # Support both legacy and current first-layer temperature keys.
        profile['first_layer_nozzle_temperature'] = (
            self._get_value('nozzle_temperature_initial_layer', '')
            or self._get_value('first_layer_temperature', '')
        )

        # Resolve bed temperature based on active bed type.
        bed_type = self._get_value('curr_bed_type', '')
        bed_key, bed_key_initial = BED_TYPE_TEMP_KEYS.get(
            bed_type, BED_TYPE_TEMP_KEYS_DEFAULT,
        )
        profile['bed_temperature'] = (
            self._get_value(bed_key, '')
            or self._get_value('hot_plate_temp', '')
        )
        profile['first_layer_bed_temperature'] = (
            self._get_value(bed_key_initial, '')
            or self._get_value('hot_plate_temp_initial_layer', '')
            or self._get_value('first_layer_bed_temperature', '')
        )


        return profile

    def _build_statistics(self) -> Dict[str, Any]:
        """Build comprehensive statistics dictionary."""
        stats = {}

        # Slicer info from header
        stats['slicer'] = self.header_info.get('slicer', '')
        stats['slicer_version'] = self.header_info.get('slicer_version', '')
        stats['generated_date'] = self.header_info.get('generated_date', '')

        # Time estimates
        stats['estimated_time'] = self.statistics.get('estimated_time', '')
        stats['estimated_first_layer_time'] = self.statistics.get('estimated_first_layer_time', '')

        # Layer info
        try:
            # Use 'is not None' check to properly handle 0 value
            total_layers_count = self.statistics.get('total_layers_count')
            if total_layers_count is not None:
                stats['total_layers'] = total_layers_count
            else:
                stats['total_layers'] = int(self.header_info.get('total_layer_number', 0) or 0)
        except (ValueError, TypeError):
            stats['total_layers'] = 0
        try:
            stats['max_height'] = float(self.header_info.get('max_z_height', 0) or 0)
        except (ValueError, TypeError):
            stats['max_height'] = 0.0
        stats['layer_height'] = self._get_value('layer_height', '')
        stats['first_layer_height'] = self._get_value('first_layer_height', '')

        # Nozzle
        stats['nozzle_diameter'] = self._get_list_value('nozzle_diameter', [])

        # Filament usage
        stats['filament_used_g'] = self.statistics.get('total_filament_used_g', 0)
        stats['filament_used_per_extruder_g'] = self.statistics.get('filament_used_g', [])
        stats['filament_used_per_extruder_mm'] = self.statistics.get('filament_used_mm', [])
        stats['filament_cost'] = self.statistics.get('total_filament_cost', 0)
        stats['filament_cost_per_extruder'] = self.statistics.get('filament_cost_per_extruder', [])
        stats['filament_changes'] = self.statistics.get('total_filament_change', 0)

        # Filament info
        stats['filament_names'] = self._get_list_value('filament_settings_id', [])
        stats['filament_types'] = self._get_list_value('filament_type', [])
        stats['filament_colors'] = self._get_list_value('filament_colour', [])
        stats['filament_density'] = self._get_list_value('filament_density', [])
        stats['filament_diameter'] = self._get_list_value('filament_diameter', [])

        # Temperatures -- resolve bed temp keys using active bed type.
        bed_type = self._get_value('curr_bed_type', '')
        bed_key, bed_key_initial = BED_TYPE_TEMP_KEYS.get(
            bed_type, BED_TYPE_TEMP_KEYS_DEFAULT,
        )
        stats['first_layer_bed_temp'] = (
            self._get_value(bed_key_initial, '')
            or self._get_value('hot_plate_temp_initial_layer', '')
            or self._get_value('first_layer_bed_temperature', '')
        )
        stats['first_layer_nozzle_temp'] = self._get_value('first_layer_temperature', '') or \
                                            self._get_value('nozzle_temperature_initial_layer', '')
        stats['nozzle_temp'] = self._get_list_value('nozzle_temperature', [])
        stats['bed_temp'] = (
            self._get_value(bed_key, '')
            or self._get_value('hot_plate_temp', '')
            or self._get_value('bed_temperature', '')
        )

        # Printer/Machine info
        stats['printer_model'] = self._get_value('printer_model', '')
        stats['gcode_flavor'] = self._get_value('gcode_flavor', '')
        stats['nozzle_type'] = self._get_value('nozzle_type', '')
        stats['curr_bed_type'] = self._get_value('curr_bed_type', '')

        # Filament extra
        stats['filament_vendor'] = self._get_list_value('filament_vendor', [])
        stats['filament_used_per_extruder_cm3'] = self.statistics.get('filament_used_cm3', [])
        stats['enable_prime_tower'] = self._get_value('enable_prime_tower', '')

        # File size
        stats['file_size_bytes'] = self.statistics.get('file_size_bytes', 0)

        return stats

    def _build_result(self) -> Dict[str, Any]:
        """Build the result dictionary."""
        return {
            'file': str(self.filepath.name),
            'profile': self._get_profile_info(),
            'profile_full': self.settings,
            'custom_global': self._get_custom_global_settings(),
            'rows': [],  # Gcode doesn't have per-object settings
            'objects': sorted(self.object_names),  # Object names list
            'statistics': self._build_statistics(),
        }
